sonar.projectKey=opencrafts-io_academia
sonar.projectName=Academia
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.dart.file.suffixes=.dart
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,build/**
