sonar.projectKey=opencrafts-io_academia
sonar.organization=opencrafts-io
sonar.projectName=academia
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.dart.file.suffixes=.dart
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,build/**,android/**,ios/**,.dart_tool/**
