// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtv7tzbhI9XqOcjsJTLAqpK09af68Pc5g',
    appId: '1:975540451403:web:206fc0539e86d3c11975ce',
    messagingSenderId: '975540451403',
    projectId: 'academia-28cec',
    authDomain: 'academia-28cec.firebaseapp.com',
    storageBucket: 'academia-28cec.firebasestorage.app',
    measurementId: 'G-0YKL358C5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdFotj76c-7MJchSB0XpoBAOhR2nlNpWM',
    appId: '1:975540451403:android:50f681d3cfcba7bc1975ce',
    messagingSenderId: '975540451403',
    projectId: 'academia-28cec',
    storageBucket: 'academia-28cec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3046oKuKmLDHWXPLIZ_a5kK7iz1WOuIQ',
    appId: '1:975540451403:ios:5594ea73e0ce460f1975ce',
    messagingSenderId: '975540451403',
    projectId: 'academia-28cec',
    storageBucket: 'academia-28cec.firebasestorage.app',
    iosBundleId: 'io.opencrafts.academia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3046oKuKmLDHWXPLIZ_a5kK7iz1WOuIQ',
    appId: '1:975540451403:ios:5594ea73e0ce460f1975ce',
    messagingSenderId: '975540451403',
    projectId: 'academia-28cec',
    storageBucket: 'academia-28cec.firebasestorage.app',
    iosBundleId: 'io.opencrafts.academia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtv7tzbhI9XqOcjsJTLAqpK09af68Pc5g',
    appId: '1:975540451403:web:75e8656928b6340c1975ce',
    messagingSenderId: '975540451403',
    projectId: 'academia-28cec',
    authDomain: 'academia-28cec.firebaseapp.com',
    storageBucket: 'academia-28cec.firebasestorage.app',
    measurementId: 'G-5H8Y6V5SBL',
  );
}
